### ISSUE TITLE
Namespace not in pascal casing

### ISSUE THREAD

**Issue by thesupersonic16** [Sajidur78/abcdefghijklmnopqrstuvwxyz#1]
The namespace for this library is not written in pascal casing which is not following with .NET's capitalisation conventions. Below I have linked a page describing about the convention.

[Capitalization Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)

**Comment by Sajidur78** [comment]
Issue fixed in 4d683562a558cc897d9aeeba259a2c8dae66c12b
