### ISSUE TITLE
Package name not properly capitalised

### ISSUE THREAD

**Issue by PTKay** [Sajidur78/abcdefghijklmnopqrstuvwxyz#2]
The NuGet package name is not using the properly capitalised, however, the package's namespace is, creating an inconsistency. The correct naming for the package would need to be `Abcdefghijklmnopqrstuvwxyz`.

**Comment by Sajidur78** [comment]
The package name is lowercase because that's what the first version was until it was fixed in 4d68356. Renaming the package would break backwards compatibility with existing build systems.
